/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class native_methods_JNIDemo */

#ifndef _Included_native_methods_JNIDemo
#define _Included_native_methods_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     native_methods_JNIDemo
 * Method:    calculateStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_native_1methods_JNIDemo_calculateStringLength
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
